### ISSUE TITLE
D button doesn't move left

### ISSUE THREAD

**Issue by 11** [oguzeroglu/ROYGBIV#22]
Hi, this is a really cool demo. Just wanted to let you know the D button isn't working in the plasma demo🙂

**Comment by oguzeroglu** [comment]
Hey! Thanks for the feedback. Normally the D button is supposed to make the character go right.

Could you tell me what kind of keyboard are you using? (US, French etc.)

Normally the engine supports US and French layouts:

```
    W                             Z
A   S   D      or French:     Q   S   D
```
