### ISSUE TITLE
AddedText in three.js r111 later is not working.

### ISSUE THREAD

**Issue by dslming** [oguzeroglu/ROYGBIV#31]

**Comment by dslming** [comment]
![image](https://user-images.githubusercontent.com/23415941/96223471-8e45ab00-0fc0-11eb-8935-c5b992d222d7.png)
r111 later, need add in AddedText.js:
```js
  this.geometry.setIndex(new THREE.BufferAttribute( new Uint32Array([0]), 1));
  this.geometry.setAttribute( 'position', new THREE.Float32BufferAttribute( [position.x, position.y, position.z], 3 ) );
```

**Comment by oguzeroglu** [comment]
Hey, 

Thanks for reaching out about this.

The thing is, ROYGBIV uses a customised fork of THREE.js. This fork is optimised for the engine itself and would no go well with non-ROYGBIV usage. Since the engine injects it's own version of THREE.js this is fine.

Best!
